#!/bin/bash
set -e # Any subsequent(*) commands which fail will cause the shell script to exit immediately

cd "$(dirname $0)/.."

echo -e "Testing..."
npm run test
npm run build

echo "SUCCESS"
exit 0
